### PR TITLE
Update HLS IP to build on 2020.2

### PR DESCRIPTION
**Pull request by giunatale**

### CODE REVIEW

**Comment by goekce** [comment]
Dear Giuseppe, I noticed that this HLS is not streaming-based like the original resizer in HelloWorld, but has an AXI_m interface. Is this decision deliberate?

**Comment by giunatale** [comment]
No that was not intentional, it slipped through as I was pulling from the updated code in the original vitis libraries. Thanks for pointing it out.

If anyone wants to update the code to restore the axis interfaces, I am more than willing to give write access to my fork.

Unfortunately I don’t really have the time to fix it myself as of now.

**Comment by goekce** [comment]
I tried using following code:
```cpp
#include "xf_resize_config.h"
#include "xf_resize_accel.hpp"

extern "C" {
void resizer(hls::stream< pkt_t > &din,
                  hls::stream< pkt_t > &dout,
                  int rows_in,
                  int cols_in,
                  int rows_out,
                  int cols_out) {
    #pragma HLS INTERFACE axis port=din
    #pragma HLS INTERFACE axis port=dout
    #pragma HLS INTERFACE s_axilite port=rows_in
    #pragma HLS INTERFACE s_axilite port=cols_in
    #pragma HLS INTERFACE s_axilite port=rows_out
    #pragma HLS INTERFACE s_axilite port=cols_out
    #pragma HLS INTERFACE s_axilite port=return

    xf::cv::Mat<TYPE, HEIGHT, WIDTH, NPC_T> in_mat(rows_in, cols_in);
    #pragma HLS stream variable=in_mat.data

    xf::cv::Mat<TYPE, NEWHEIGHT, NEWWIDTH, NPC_T> out_mat(rows_out, cols_out);
    #pragma HLS stream variable=out_mat.data

    #pragma HLS DATAFLOW
    xf::cv::axiStrm2xfMat<DATA_PORT_WIDTH, TYPE, HEIGHT, WIDTH, NPC_T>(din, in_mat);
    xf::cv::resize<INTERPOLATION, TYPE, HEIGHT, WIDTH, NEWHEIGHT, NEWWIDTH, NPC_T, MAXDOWNSCALE>(in_mat, out_mat);
    xf::cv::xfMat2axiStrm<DATA_PORT_WIDTH, TYPE, NEWHEIGHT, NEWWIDTH, NPC_T>(out_mat, dout);
}
}
```

`xf_resize_accel.hpp`:
```cpp
#ifndef _XF_RESIZE_ACCEL_
#define _XF_RESIZE_ACCEL_

#include "xf_config_params.h"

typedef ap_axiu<DATA_PORT_WIDTH, 0, 0, 0> pkt_t;

void resize_accel(hls::stream< pkt_t > &din,
                  hls::stream< pkt_t > &dout,
                  int rows_in,
                  int cols_in,
                  int rows_out,
                  int cols_out);
#endif
```

`xf_config_params.h`:
```cpp
#define RO 0 // Resource Optimized (8-pixel implementation)
#define NO 1 // Normal Operation (1-pixel implementation)

// port widths
#define DATA_PORT_WIDTH 64
// Xilinx files use INPUT_PTR_WIDTH & _HEIGHT
#define INPUT_PTR_WIDTH DATA_PORT_WIDTH
#define OUTPUT_PTR_WIDTH DATA_PORT_WIDTH

// For Nearest Neighbor & Bilinear Interpolation, max down scale factor 2 for
// all 1-pixel modes, and for upscale in x direction
#define MAXDOWNSCALE 2

#define RGB 1
#define GRAY 0
/* Interpolation type*/
#define INTERPOLATION 1
// 0 - Nearest Neighbor Interpolation
// 1 - Bilinear Interpolation
// 2 - AREA Interpolation

/* Input image Dimensions */
#define WIDTH 3840  // Maximum Input image width
#define HEIGHT 2160 // Maximum Input image height

/* Output image Dimensions */
#define NEWWIDTH 1920  // Maximum output image width
#define NEWHEIGHT 1080 // Maximum output image height
```

The DMA transmit completes, but DMA receive does not. Maybe this helps someone as a starter.

**Comment by yunqu** [comment]
There is a fix that I mentioned on discuss.pynq.io: https://discuss.pynq.io/t/vitis-vision-core-fails-on-pynq-v2-5-1/1822/19?u=rock

Basically you need to change the axis2mat and mat2axis call. After that it should be all working as before with streaming interface. I don't think we should approve this PR since it changes the behavior of the original IP.

**Comment by goekce** [comment]
The fix mentioned does not seem to work in 2020.2 (Vitis HLS).

**Comment by giunatale** [comment]
I can provide write access to my fork if anyone wants to take this in and commit the required fixes. Unfortunately I can't take this on myself.

Thanks for spotting the error and getting this sorted!

**Comment by Wardo82** [comment]
Hello Everybody, any updates on this topic? Can't make it work on Vitis HLS 2020.1 with any fix mentioned here nor in the link above.

**Pull request merged**
