### PR TITLE
Update to 2020.2

### LINKED ISSUE #22: Error Synthesising the resizer HLS
Dear,
We try to use your example for demo PYNQ on the Ultra96.
We use vitis 20.02 package on Ubuntu20.04, synthesing the resize HLS IP runs in code errors:

ERROR: [HLS 207-3332] type 'hls::stream<DATATYPE, 2>' (aka 'stream<ap_uint<24>, 2>') does not provide a subscript operator: xf_resize_accel.cpp:42:11
ERROR: [HLS 207-3332] type 'hls::stream<DATATYPE, 2>' (aka 'stream<ap_uint<24>, 2>') does not provide a subscript operator: xf_resize_accel.cpp:62:38
ERROR: [HLS 207-2538] declaration of 'resize_accel' has a different language linkage: xf_resize_accel.cpp:68:53

Before we dig deeper into the C++ code, is this related to HLS settings  -as we use vitis_hls, not the 2019 vivado_hls ?
Or could the Vitis Vision-library have changed, we copied it from the repo.

### PR DESCRIPTION
**Pull request by mariodruiz**
- Fix the kernel to work with streams properly
- Some housekeeping with repeated files

This fixes #22 #20 #25

### CODE REVIEW

**Comment by jancumps** [comment]
I have tested mariodruiz:image_v2.7_2020.2 with Vivado 2020.2 and Vitis HLS 2020.2, and it works.

note: I didn't run the get/build on the Pynq-Z2 board but on my development Windows 10 device, starting from Github clone

git clone -b image_v2.7_2020.2 https://github.com/mariodruiz/PYNQ-HelloWorld.git --recursive

start Vitis 2020.2 TCL
cd PYNQ-HelloWorld\boards\ip
vitis_hls -f build.tcl -tclargs ./vitis_lib/vision/L1/include/ resize/resize/impl/ip/component.xml

start Vivado 2020.2 TCL

cd PYNQ-HelloWorld/boards/Pynq-Z2/resizer
vivado -mode batch -source resizer.tcl -notrace
vivado -mode batch -source build_bitstream.tcl -notrace

Moved the PYNQ-HelloWorld/pynq_helloworld/notebooks/edge/*.ipynb files, and the .hwh and .bit file to the Zynq-Z2 and tested.

**Comment by jancumps** [comment]
I tried this, and everything builds OK in Vitis HLS and Vivado, both 2020.2, Pynq 2.6

The accelerated function doesn't return though. It hangs on execution:

image

It works if I download and use the .bit file refered to in [https://github.com/Xilinx/PYNQ-HelloWorld/blob/master/pynq_helloworld/notebooks/edge/resizer.bit.link](https://github.com/Xilinx/PYNQ-HelloWorld/blob/master/pynq_helloworld/notebooks/edge/resizer.bit.link) for the Z2  ([https://www.xilinx.com/bin/public/openDownload?filename=pynqhelloworld.resizer.pynqz2.bit](https://www.xilinx.com/bin/public/openDownload?filename=pynqhelloworld.resizer.pynqz2.bit)).
Not with the bit file generated by the Vitis HLS and Vivado (both 2020.2)  scripts. 

I will try again as soon as I have a 2.7 SD made.

**Comment by mariodruiz** [comment]
Are you using Pynq-Z2?

**Comment by jancumps** [comment]
> Are you using Pynq-Z2?

Yes. I am using a Zynq-Z2 with Pynq2.6. I used the Zynq-Z2 folder to make the Vivado project.
I used your repository/branch for this pull request: **mariodruiz:image_v2.7_2020.2**

**Comment by mariodruiz** [comment]
Did you use Vivado/Vitis HLS 2020.2?

**Comment by jancumps** [comment]
> Did you use Vivado/Vitis HLS 2020.2?

Correct. I used version 2020.2 for both tools. And both Vitis HLS and Vivado gave a successful build.

edit: I used this command to get the source + vitis_lib dependecies:
`git clone -b image_v2.7_2020.2 https://github.com/mariodruiz/PYNQ-HelloWorld.git --recursive`

**Comment by mariodruiz** [comment]
PYNQ SD 2.7 has just been released. Can you please burn an SD card with the new version and try again?

**Comment by jancumps** [comment]
I will test and report back.

**Comment by mariodruiz** [comment]
Apologies, I had forgotten to push the latest changes. Please try with commit 02da05462a7a8bce544cc9eb8e7017f873bbc58c, it should work with PYNQ 2.6 and 2.7

**Comment by jancumps** [comment]
Testing ...

**Comment by jancumps** [comment]
Success !
image

Vitis HLS 2020.2
Vivado 2020.2
Pynq 2.6 (I will test with 2.7 later, need to get a new SD card)

**Comment by mariodruiz** [comment]
Just tested on 2.7. But, if you can double check it would be great!

**Comment by jancumps** [comment]
> Just tested on 2.7. But, if you can double check it would be great!

Checked. It works with 2.7 too. Thank you.

**Pull request merged**
